### ISSUE TITLE
Not installing with Atom 1.12.5 and Windows 7 Pro x64 SP1

### ISSUE THREAD

**Issue by odintsaq** [p-e-w/language-javascript-semantic#37]
Hi. I have tried installing it via the package installer and it fails (miserably), but also I get an error when inserting the unzipped package into the Atom/packages folder.

**Comment by p-e-w** [comment]
This project is *on hold* pending resolution of [atom#8669](https://github.com/atom/atom/issues/8669). I'm tired of chasing an undocumented private API.

Because the token data structure is not part of Atom's public API, it can (and does) get modified even between minor releases. I will not be updating this package anymore until that fundamental problem has been solved. There needs to be an "official" method for using non-regex-based tokenizers.

**Comment by reohjs** [comment]
https://github.com/p-e-w/language-javascript-semantic/issues/34#issuecomment-153007739

**Comment by odintsaq** [comment]
@p-e-w Thank you for your reply. And I can understand why you won't update anymore
@reohjs Thanks for the tip. I will try it out.
Cheers!
